/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APISubDataProcessorResponseDTO } from './subDataProcessorResponseDTO';
import { APINamedEntityDTO } from './namedEntityDTO';
import { APIDataProcessingRegistrationDTOOversightCompleted } from './dataProcessingRegistrationDTOOversightCompleted';
import { APINamedEntityWithEnabledStatusDTO } from './namedEntityWithEnabledStatusDTO';
import { APIDataProcessingRegistrationDTOOversightOptions } from './dataProcessingRegistrationDTOOversightOptions';
import { APIShallowOrganizationDTO } from './shallowOrganizationDTO';
import { APINamedEntityWithExpirationStatusDTO } from './namedEntityWithExpirationStatusDTO';
import { APIDataProcessingRegistrationDTOOversightInterval } from './dataProcessingRegistrationDTOOversightInterval';
import { APIDataProcessingRegistrationDTOAgreementConcluded } from './dataProcessingRegistrationDTOAgreementConcluded';
import { APIReferenceDTO } from './referenceDTO';
import { APIAssignedRoleDTO } from './assignedRoleDTO';
import { APIYesNoUndecidedOption } from './yesNoUndecidedOption';
import { APIDataProcessingRegistrationDTOBasisForTransfer } from './dataProcessingRegistrationDTOBasisForTransfer';
import { APIDataProcessingRegistrationOversightDateDTO } from './dataProcessingRegistrationOversightDateDTO';
import { APIDataProcessingRegistrationDTODataResponsible } from './dataProcessingRegistrationDTODataResponsible';


export interface APIDataProcessingRegistrationDTO { 
    uuid?: string;
    assignedRoles?: Array<APIAssignedRoleDTO> | null;
    references?: Array<APIReferenceDTO> | null;
    itSystems?: Array<APINamedEntityWithEnabledStatusDTO> | null;
    oversightInterval?: APIDataProcessingRegistrationDTOOversightInterval | null;
    hasSubDataProcessors?: APIYesNoUndecidedOption | null;
    dataProcessors?: Array<APIShallowOrganizationDTO> | null;
    subDataProcessors?: Array<APISubDataProcessorResponseDTO> | null;
    agreementConcluded?: APIDataProcessingRegistrationDTOAgreementConcluded | null;
    transferToInsecureThirdCountries?: APIYesNoUndecidedOption | null;
    insecureThirdCountries?: Array<APINamedEntityWithExpirationStatusDTO> | null;
    basisForTransfer?: APIDataProcessingRegistrationDTOBasisForTransfer | null;
    dataResponsible?: APIDataProcessingRegistrationDTODataResponsible | null;
    oversightOptions?: APIDataProcessingRegistrationDTOOversightOptions | null;
    oversightCompleted?: APIDataProcessingRegistrationDTOOversightCompleted | null;
    oversightDates?: Array<APIDataProcessingRegistrationOversightDateDTO> | null;
    associatedContracts?: Array<APINamedEntityDTO> | null;
    oversightScheduledInspectionDate?: string | null;
    lastChangedByName?: string | null;
    lastChangedAt?: string;
    isActiveAccordingToMainContract?: boolean;
    mainContractId?: number | null;
    id?: number;
    name?: string | null;
}

