/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIEdmContainerElementKind = 0 | 1 | 2 | 3 | 4;

export const APIEdmContainerElementKind = {
    NUMBER_0: 0 as APIEdmContainerElementKind,
    NUMBER_1: 1 as APIEdmContainerElementKind,
    NUMBER_2: 2 as APIEdmContainerElementKind,
    NUMBER_3: 3 as APIEdmContainerElementKind,
    NUMBER_4: 4 as APIEdmContainerElementKind
};

