/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIEdmExpressionKind = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25;

export const APIEdmExpressionKind = {
    NUMBER_0: 0 as APIEdmExpressionKind,
    NUMBER_1: 1 as APIEdmExpressionKind,
    NUMBER_2: 2 as APIEdmExpressionKind,
    NUMBER_3: 3 as APIEdmExpressionKind,
    NUMBER_4: 4 as APIEdmExpressionKind,
    NUMBER_5: 5 as APIEdmExpressionKind,
    NUMBER_6: 6 as APIEdmExpressionKind,
    NUMBER_7: 7 as APIEdmExpressionKind,
    NUMBER_8: 8 as APIEdmExpressionKind,
    NUMBER_9: 9 as APIEdmExpressionKind,
    NUMBER_10: 10 as APIEdmExpressionKind,
    NUMBER_11: 11 as APIEdmExpressionKind,
    NUMBER_12: 12 as APIEdmExpressionKind,
    NUMBER_13: 13 as APIEdmExpressionKind,
    NUMBER_14: 14 as APIEdmExpressionKind,
    NUMBER_15: 15 as APIEdmExpressionKind,
    NUMBER_16: 16 as APIEdmExpressionKind,
    NUMBER_17: 17 as APIEdmExpressionKind,
    NUMBER_18: 18 as APIEdmExpressionKind,
    NUMBER_19: 19 as APIEdmExpressionKind,
    NUMBER_20: 20 as APIEdmExpressionKind,
    NUMBER_21: 21 as APIEdmExpressionKind,
    NUMBER_22: 22 as APIEdmExpressionKind,
    NUMBER_23: 23 as APIEdmExpressionKind,
    NUMBER_24: 24 as APIEdmExpressionKind,
    NUMBER_25: 25 as APIEdmExpressionKind
};

