/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIEdmSchemaElementKind = 0 | 1 | 2 | 3 | 4 | 5;

export const APIEdmSchemaElementKind = {
    NUMBER_0: 0 as APIEdmSchemaElementKind,
    NUMBER_1: 1 as APIEdmSchemaElementKind,
    NUMBER_2: 2 as APIEdmSchemaElementKind,
    NUMBER_3: 3 as APIEdmSchemaElementKind,
    NUMBER_4: 4 as APIEdmSchemaElementKind,
    NUMBER_5: 5 as APIEdmSchemaElementKind
};

