/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIEdmTypeKind = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export const APIEdmTypeKind = {
    NUMBER_0: 0 as APIEdmTypeKind,
    NUMBER_1: 1 as APIEdmTypeKind,
    NUMBER_2: 2 as APIEdmTypeKind,
    NUMBER_3: 3 as APIEdmTypeKind,
    NUMBER_4: 4 as APIEdmTypeKind,
    NUMBER_5: 5 as APIEdmTypeKind,
    NUMBER_6: 6 as APIEdmTypeKind,
    NUMBER_7: 7 as APIEdmTypeKind,
    NUMBER_8: 8 as APIEdmTypeKind,
    NUMBER_9: 9 as APIEdmTypeKind
};

