/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIIEdmVocabularyAnnotationValue } from './iEdmVocabularyAnnotationValue';
import { APIIEdmVocabularyAnnotationTerm } from './iEdmVocabularyAnnotationTerm';


export interface APIIEdmVocabularyAnnotation { 
    readonly qualifier?: string | null;
    term?: APIIEdmVocabularyAnnotationTerm | null;
    readonly target?: object | null;
    value?: APIIEdmVocabularyAnnotationValue | null;
    readonly usesDefault?: boolean;
}

