/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIIEdmVocabularyAnnotation } from './iEdmVocabularyAnnotation';
import { APIIEdmSchemaElement } from './iEdmSchemaElement';
import { APIIEdmEntityContainerElementContainer } from './iEdmEntityContainerElementContainer';


export interface APIIEdmModel { 
    readonly schemaElements?: Array<APIIEdmSchemaElement> | null;
    readonly vocabularyAnnotations?: Array<APIIEdmVocabularyAnnotation> | null;
    readonly referencedModels?: Array<APIIEdmModel> | null;
    readonly declaredNamespaces?: Array<string> | null;
    readonly directValueAnnotationsManager?: object | null;
    entityContainer?: APIIEdmEntityContainerElementContainer | null;
}

