/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIEdmSchemaElementKind } from './edmSchemaElementKind';
import { APIIEdmTermType } from './iEdmTermType';


export interface APIIEdmTerm { 
    type?: APIIEdmTermType | null;
    readonly appliesTo?: string | null;
    readonly defaultValue?: string | null;
    readonly schemaElementKind?: APIEdmSchemaElementKind;
    readonly namespace?: string | null;
    readonly name?: string | null;
}

