/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIODataSingletonInfo } from './oDataSingletonInfo';
import { APIODataEntitySetInfo } from './oDataEntitySetInfo';
import { APIODataEntitySetInfoTypeAnnotation } from './oDataEntitySetInfoTypeAnnotation';
import { APIODataFunctionImportInfo } from './oDataFunctionImportInfo';


export interface APIODataServiceDocument { 
    entitySets?: Array<APIODataEntitySetInfo> | null;
    singletons?: Array<APIODataSingletonInfo> | null;
    functionImports?: Array<APIODataFunctionImportInfo> | null;
    typeAnnotation?: APIODataEntitySetInfoTypeAnnotation | null;
}

