/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIAccessModifier } from './accessModifier';
import { APIOrganizationDTOConfig } from './organizationDTOConfig';
import { APIOrganizationAndDefaultUnitDTODefaultOrgUnit } from './organizationAndDefaultUnitDTODefaultOrgUnit';
import { APIOrganizationDTOContactPerson } from './organizationDTOContactPerson';


export interface APIOrganizationDTO { 
    phone?: string | null;
    adress?: string | null;
    email?: string | null;
    cvr?: string | null;
    foreignCvr?: string | null;
    typeId?: number;
    accessModifier?: APIAccessModifier;
    config?: APIOrganizationDTOConfig | null;
    root?: APIOrganizationAndDefaultUnitDTODefaultOrgUnit | null;
    lastChanged?: string;
    lastChangedByUserId?: number;
    uuid?: string;
    contactPersonId?: number | null;
    contactPerson?: APIOrganizationDTOContactPerson | null;
    id?: number;
    name?: string | null;
}

