/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIOrganizationDTOContactPerson } from './organizationDTOContactPerson';
import { APIOrganizationRole } from './organizationRole';


export interface APIOrganizationRightDTO { 
    organizationId?: number;
    organizationUuid?: string;
    organizationName?: string | null;
    role?: APIOrganizationRightDTO.RoleEnum;
    userId?: number;
    user?: APIOrganizationDTOContactPerson | null;
    userName?: string | null;
    userEmail?: string | null;
    lastChanged?: string;
    lastChangedByUserId?: number;
    objectOwnerName?: string | null;
    objectOwnerLastName?: string | null;
    readonly objectOwnerFullName?: string | null;
    defaultOrgUnitName?: string | null;
}
export namespace APIOrganizationRightDTO {
    export type RoleEnum = 'User' | 'LocalAdmin' | 'OrganizationModuleAdmin' | 'SystemModuleAdmin' | 'ContractModuleAdmin' | 'GlobalAdmin' | 'RightsHolderAccess';
    export const RoleEnum = {
        User: 'User' as RoleEnum,
        LocalAdmin: 'LocalAdmin' as RoleEnum,
        OrganizationModuleAdmin: 'OrganizationModuleAdmin' as RoleEnum,
        SystemModuleAdmin: 'SystemModuleAdmin' as RoleEnum,
        ContractModuleAdmin: 'ContractModuleAdmin' as RoleEnum,
        GlobalAdmin: 'GlobalAdmin' as RoleEnum,
        RightsHolderAccess: 'RightsHolderAccess' as RoleEnum
    };
}


