/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIOrganizationRole = 0 | 1 | 2 | 4 | 5 | 7 | 8;

export const APIOrganizationRole = {
    NUMBER_0: 0 as APIOrganizationRole,
    NUMBER_1: 1 as APIOrganizationRole,
    NUMBER_2: 2 as APIOrganizationRole,
    NUMBER_4: 4 as APIOrganizationRole,
    NUMBER_5: 5 as APIOrganizationRole,
    NUMBER_7: 7 as APIOrganizationRole,
    NUMBER_8: 8 as APIOrganizationRole
};

