/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APISystemDeleteConflict = 0 | 1 | 2;

export const APISystemDeleteConflict = {
    NUMBER_0: 0 as APISystemDeleteConflict,
    NUMBER_1: 1 as APISystemDeleteConflict,
    NUMBER_2: 2 as APISystemDeleteConflict
};

