/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIYearMonthIntervalOption = 0 | 1 | 2 | 3 | 4;

export const APIYearMonthIntervalOption = {
    NUMBER_0: 0 as APIYearMonthIntervalOption,
    NUMBER_1: 1 as APIYearMonthIntervalOption,
    NUMBER_2: 2 as APIYearMonthIntervalOption,
    NUMBER_3: 3 as APIYearMonthIntervalOption,
    NUMBER_4: 4 as APIYearMonthIntervalOption
};

