/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIYesNoUndecidedOption = 0 | 1 | 2;

export const APIYesNoUndecidedOption = {
    NUMBER_0: 0 as APIYesNoUndecidedOption,
    NUMBER_1: 1 as APIYesNoUndecidedOption,
    NUMBER_2: 2 as APIYesNoUndecidedOption
};

