/**
 * KITOS API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIYesNoIrrelevantOption = 0 | 1 | 2 | 3;

export const APIYesNoIrrelevantOption = {
    NUMBER_0: 0 as APIYesNoIrrelevantOption,
    NUMBER_1: 1 as APIYesNoIrrelevantOption,
    NUMBER_2: 2 as APIYesNoIrrelevantOption,
    NUMBER_3: 3 as APIYesNoIrrelevantOption
};

