/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIAlertType } from './alertType';


export interface APIAlertResponseDTO { 
    uuid: string;
    entityUuid: string;
    name?: string | null;
    alertType?: APIAlertResponseDTO.AlertTypeEnum;
    message?: string | null;
    created?: string | null;
}
export namespace APIAlertResponseDTO {
    export type AlertTypeEnum = 'Advis';
    export const AlertTypeEnum = {
        Advis: 'Advis' as AlertTypeEnum
    };
}


