/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIArchiveDutyChoice } from './archiveDutyChoice';
import { APIJournalPeriodResponseDTO } from './journalPeriodResponseDTO';
import { APIArchivingRegistrationsResponseDTOSupplier } from './archivingRegistrationsResponseDTOSupplier';


export interface APIArchivingRegistrationsResponseDTO { 
    archiveDuty?: APIArchiveDutyChoice | null;
    type?: APIArchivingRegistrationsResponseDTOType | null;
    location?: APIArchivingRegistrationsResponseDTOType | null;
    testLocation?: APIArchivingRegistrationsResponseDTOType | null;
    supplier?: APIArchivingRegistrationsResponseDTOSupplier | null;
    active?: boolean | null;
    notes?: string | null;
    frequencyInMonths?: number | null;
    documentBearing?: boolean | null;
    journalPeriods: Array<APIJournalPeriodResponseDTO>;
}

