/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIArchiveDutyChoice = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const APIArchiveDutyChoice = {
    NUMBER_0: 0 as APIArchiveDutyChoice,
    NUMBER_1: 1 as APIArchiveDutyChoice,
    NUMBER_2: 2 as APIArchiveDutyChoice,
    NUMBER_3: 3 as APIArchiveDutyChoice,
    NUMBER_4: 4 as APIArchiveDutyChoice,
    NUMBER_5: 5 as APIArchiveDutyChoice,
    NUMBER_6: 6 as APIArchiveDutyChoice,
    NUMBER_7: 7 as APIArchiveDutyChoice
};

