/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIBaseNotificationPropertiesWriteRequestDTOCcs } from './baseNotificationPropertiesWriteRequestDTOCcs';
import { APIBaseNotificationPropertiesWriteRequestDTOReceivers } from './baseNotificationPropertiesWriteRequestDTOReceivers';


export interface APIBaseNotificationPropertiesWriteRequestDTO { 
    subject: string;
    body?: string | null;
    ccs?: APIBaseNotificationPropertiesWriteRequestDTOCcs | null;
    receivers: APIBaseNotificationPropertiesWriteRequestDTOReceivers;
}

