/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APICommonOrderByProperty = 0 | 1 | 2;

export const APICommonOrderByProperty = {
    NUMBER_0: 0 as APICommonOrderByProperty,
    NUMBER_1: 1 as APICommonOrderByProperty,
    NUMBER_2: 2 as APICommonOrderByProperty
};

