/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIConnectionUpdateOrganizationUnitChangeType } from './connectionUpdateOrganizationUnitChangeType';


export interface APIConnectionUpdateOrganizationUnitConsequenceDTO { 
    uuid?: string;
    name?: string | null;
    category?: APIConnectionUpdateOrganizationUnitConsequenceDTO.CategoryEnum;
    description?: string | null;
}
export namespace APIConnectionUpdateOrganizationUnitConsequenceDTO {
    export type CategoryEnum = 'Added' | 'Renamed' | 'Moved' | 'Deleted' | 'Converted' | 'RootChanged';
    export const CategoryEnum = {
        Added: 'Added' as CategoryEnum,
        Renamed: 'Renamed' as CategoryEnum,
        Moved: 'Moved' as CategoryEnum,
        Deleted: 'Deleted' as CategoryEnum,
        Converted: 'Converted' as CategoryEnum,
        RootChanged: 'RootChanged' as CategoryEnum
    };
}


