/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIContractGeneralDataWriteRequestDTOValidity } from './contractGeneralDataWriteRequestDTOValidity';


export interface APIContractWriteRequestDTOGeneral { 
    contractId?: string | null;
    contractTypeUuid?: string | null;
    contractTemplateUuid?: string | null;
    agreementElementUuids?: Array<string> | null;
    notes?: string | null;
    validity?: APIContractGeneralDataWriteRequestDTOValidity | null;
    criticalityUuid?: string | null;
}

