/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIContractValidityResponseDTO } from './contractValidityResponseDTO';


export interface APIContractGeneralDataResponseDTO { 
    contractId?: string | null;
    contractType?: APIIdentityNamePairResponseDTO;
    contractTemplate?: APIIdentityNamePairResponseDTO;
    agreementElements: Array<APIIdentityNamePairResponseDTO>;
    notes?: string | null;
    validity: APIContractValidityResponseDTO;
    criticality?: APIIdentityNamePairResponseDTO;
}

