/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIItContractValidationErrorChoice } from './itContractValidationErrorChoice';


export interface APIContractGeneralDataResponseDTOValidity { 
    valid: boolean;
    enforcedValid: boolean;
    validFrom?: string | null;
    validTo?: string | null;
    requireValidParent: boolean;
    validationErrors?: Array<APIItContractValidationErrorChoice> | null;
}

