/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIDataProcessorRegistrationSubDataProcessorWriteRequestDTO } from './dataProcessorRegistrationSubDataProcessorWriteRequestDTO';
import { APIYesNoUndecidedChoice } from './yesNoUndecidedChoice';
import { APIYesNoIrrelevantChoice } from './yesNoIrrelevantChoice';


export interface APICreateDataProcessingRegistrationRequestDTOGeneral { 
    dataResponsibleUuid?: string | null;
    dataResponsibleRemark?: string | null;
    isAgreementConcluded?: APIYesNoIrrelevantChoice | null;
    isAgreementConcludedRemark?: string | null;
    agreementConcludedAt?: string | null;
    basisForTransferUuid?: string | null;
    transferToInsecureThirdCountries?: APIYesNoUndecidedChoice | null;
    insecureCountriesSubjectToDataTransferUuids?: Array<string> | null;
    dataProcessorUuids?: Array<string> | null;
    hasSubDataProcessors?: APIYesNoUndecidedChoice | null;
    subDataProcessors?: Array<APIDataProcessorRegistrationSubDataProcessorWriteRequestDTO> | null;
    mainContractUuid?: string | null;
    responsibleOrganizationUnitUuid?: string | null;
}

