/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIExternalReferenceDataWriteRequestDTO } from './externalReferenceDataWriteRequestDTO';
import { APIDataProcessingRegistrationGeneralDataWriteRequestDTO } from './dataProcessingRegistrationGeneralDataWriteRequestDTO';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';
import { APIDataProcessingRegistrationOversightWriteRequestDTO } from './dataProcessingRegistrationOversightWriteRequestDTO';


export interface APICreateDataProcessingRegistrationRequestDTO { 
    general?: APIDataProcessingRegistrationGeneralDataWriteRequestDTO;
    systemUsageUuids?: Array<string> | null;
    oversight?: APIDataProcessingRegistrationOversightWriteRequestDTO;
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
    organizationUuid: string;
    name: string | null;
    externalReferences?: Array<APIExternalReferenceDataWriteRequestDTO> | null;
}

