/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIContractPaymentModelDataWriteRequestDTO } from './contractPaymentModelDataWriteRequestDTO';
import { APIContractAgreementPeriodDataWriteRequestDTO } from './contractAgreementPeriodDataWriteRequestDTO';
import { APIExternalReferenceDataWriteRequestDTO } from './externalReferenceDataWriteRequestDTO';
import { APIContractGeneralDataWriteRequestDTO } from './contractGeneralDataWriteRequestDTO';
import { APIContractResponsibleDataWriteRequestDTO } from './contractResponsibleDataWriteRequestDTO';
import { APIContractSupplierDataWriteRequestDTO } from './contractSupplierDataWriteRequestDTO';
import { APIContractProcurementDataWriteRequestDTO } from './contractProcurementDataWriteRequestDTO';
import { APIContractPaymentsDataWriteRequestDTO } from './contractPaymentsDataWriteRequestDTO';
import { APIContractTerminationDataWriteRequestDTO } from './contractTerminationDataWriteRequestDTO';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';


export interface APICreateNewContractRequestDTO { 
    parentContractUuid?: string | null;
    general?: APIContractGeneralDataWriteRequestDTO;
    procurement?: APIContractProcurementDataWriteRequestDTO;
    supplier?: APIContractSupplierDataWriteRequestDTO;
    responsible?: APIContractResponsibleDataWriteRequestDTO;
    systemUsageUuids?: Array<string> | null;
    dataProcessingRegistrationUuids?: Array<string> | null;
    paymentModel?: APIContractPaymentModelDataWriteRequestDTO;
    agreementPeriod?: APIContractAgreementPeriodDataWriteRequestDTO;
    termination?: APIContractTerminationDataWriteRequestDTO;
    payments?: APIContractPaymentsDataWriteRequestDTO;
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
    organizationUuid: string;
    name: string;
    externalReferences?: Array<APIExternalReferenceDataWriteRequestDTO> | null;
}

