/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIExternalReferenceDataWriteRequestDTO } from './externalReferenceDataWriteRequestDTO';
import { APILocalKLEDeviationsRequestDTO } from './localKLEDeviationsRequestDTO';
import { APIOrganizationUsageWriteRequestDTO } from './organizationUsageWriteRequestDTO';
import { APIGeneralDataWriteRequestDTO } from './generalDataWriteRequestDTO';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';
import { APIGDPRWriteRequestDTO } from './gDPRWriteRequestDTO';
import { APIArchivingCreationRequestDTO } from './archivingCreationRequestDTO';


export interface APICreateItSystemUsageRequestDTO { 
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
    organizationUsage?: APIOrganizationUsageWriteRequestDTO;
    localKleDeviations?: APILocalKLEDeviationsRequestDTO;
    gdpr?: APIGDPRWriteRequestDTO;
    systemUuid: string;
    organizationUuid: string;
    general?: APIGeneralDataWriteRequestDTO;
    externalReferences?: Array<APIExternalReferenceDataWriteRequestDTO> | null;
    archiving?: APIArchivingCreationRequestDTO;
}

