/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APICreateItSystemUsageRequestDTOOrganizationUsage } from './createItSystemUsageRequestDTOOrganizationUsage';
import { APIExternalReferenceDataWriteRequestDTO } from './externalReferenceDataWriteRequestDTO';
import { APICreateItSystemUsageRequestDTOLocalKleDeviations } from './createItSystemUsageRequestDTOLocalKleDeviations';
import { APICreateItSystemUsageRequestDTOGdpr } from './createItSystemUsageRequestDTOGdpr';
import { APICreateItSystemUsageRequestDTOArchiving } from './createItSystemUsageRequestDTOArchiving';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';
import { APICreateItSystemUsageRequestDTOGeneral } from './createItSystemUsageRequestDTOGeneral';


export interface APICreateItSystemUsageRequestDTO { 
    systemUuid: string;
    organizationUuid: string;
    general?: APICreateItSystemUsageRequestDTOGeneral | null;
    externalReferences?: Array<APIExternalReferenceDataWriteRequestDTO> | null;
    archiving?: APICreateItSystemUsageRequestDTOArchiving | null;
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
    organizationUsage?: APICreateItSystemUsageRequestDTOOrganizationUsage | null;
    localKleDeviations?: APICreateItSystemUsageRequestDTOLocalKleDeviations | null;
    gdpr?: APICreateItSystemUsageRequestDTOGdpr | null;
}

