/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchiveDutyChoice } from './archiveDutyChoice';
import { APIJournalPeriodDTO } from './journalPeriodDTO';


export interface APICreateItSystemUsageRequestDTOArchiving { 
    journalPeriods?: Array<APIJournalPeriodDTO> | null;
    archiveDuty?: APIArchiveDutyChoice | null;
    typeUuid?: string | null;
    locationUuid?: string | null;
    testLocationUuid?: string | null;
    supplierOrganizationUuid?: string | null;
    active?: boolean | null;
    notes?: string | null;
    frequencyInMonths?: number | null;
    documentBearing?: boolean | null;
}

