/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIDataProcessorRegistrationSubDataProcessorResponseDTO } from './dataProcessorRegistrationSubDataProcessorResponseDTO';
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIYesNoUndecidedChoice } from './yesNoUndecidedChoice';
import { APIYesNoIrrelevantChoice } from './yesNoIrrelevantChoice';
import { APIShallowOrganizationResponseDTO } from './shallowOrganizationResponseDTO';


export interface APIDataProcessingRegistrationResponseDTOGeneral { 
    dataResponsible?: APIArchivingRegistrationsResponseDTOType | null;
    dataResponsibleRemark?: string | null;
    isAgreementConcluded?: APIYesNoIrrelevantChoice | null;
    isAgreementConcludedRemark?: string | null;
    agreementConcludedAt?: string | null;
    basisForTransfer?: APIArchivingRegistrationsResponseDTOType | null;
    transferToInsecureThirdCountries?: APIYesNoUndecidedChoice | null;
    insecureCountriesSubjectToDataTransfer: Array<APIIdentityNamePairResponseDTO>;
    dataProcessors: Array<APIShallowOrganizationResponseDTO>;
    hasSubDataProcessors?: APIYesNoUndecidedChoice | null;
    subDataProcessors: Array<APIDataProcessorRegistrationSubDataProcessorResponseDTO>;
    valid: boolean;
    mainContract?: APIArchivingRegistrationsResponseDTOType | null;
    associatedContracts?: Array<APIIdentityNamePairResponseDTO> | null;
    responsibleOrganizationUnit?: APIArchivingRegistrationsResponseDTOType | null;
}

