/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIOversightIntervalChoice } from './oversightIntervalChoice';
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIYesNoUndecidedChoice } from './yesNoUndecidedChoice';
import { APIOversightDateDTO } from './oversightDateDTO';


export interface APIDataProcessingRegistrationOversightResponseDTO { 
    oversightOptions: Array<APIIdentityNamePairResponseDTO>;
    oversightOptionsRemark?: string | null;
    oversightInterval?: APIOversightIntervalChoice | null;
    oversightIntervalRemark?: string | null;
    /**
     *  (Supplier Field)
     */
    isOversightCompleted?: APIYesNoUndecidedChoice | null;
    oversightCompletedRemark?: string | null;
    oversightScheduledInspectionDate?: string | null;
    oversightDates: Array<APIOversightDateDTO>;
}

