/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIYesNoUndecidedChoice } from './yesNoUndecidedChoice';
import { APIDataProcessingRegistrationResponseDTOOrganizationContext } from './dataProcessingRegistrationResponseDTOOrganizationContext';


export interface APIDataProcessorRegistrationSubDataProcessorResponseDTO { 
    dataProcessorOrganization: APIDataProcessingRegistrationResponseDTOOrganizationContext;
    basisForTransfer?: APIArchivingRegistrationsResponseDTOType | null;
    transferToInsecureThirdCountry?: APIYesNoUndecidedChoice | null;
    insecureThirdCountrySubjectToDataProcessing?: APIArchivingRegistrationsResponseDTOType | null;
}

