/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIDataProcessingRegistrationResponseDTOGeneral } from './dataProcessingRegistrationResponseDTOGeneral';
import { APIRoleAssignmentResponseDTO } from './roleAssignmentResponseDTO';
import { APIDataProcessingRegistrationResponseDTOOversight } from './dataProcessingRegistrationResponseDTOOversight';
import { APIDataProcessingRegistrationResponseDTOCreatedBy } from './dataProcessingRegistrationResponseDTOCreatedBy';
import { APIDataProcessingRegistrationResponseDTOOrganizationContext } from './dataProcessingRegistrationResponseDTOOrganizationContext';
import { APIExternalReferenceDataResponseDTO } from './externalReferenceDataResponseDTO';


export interface APIDataProcessingRegistrationResponseDTO { 
    name: string;
    uuid: string;
    createdBy: APIDataProcessingRegistrationResponseDTOCreatedBy;
    lastModified: string;
    lastModifiedBy: APIDataProcessingRegistrationResponseDTOCreatedBy;
    organizationContext: APIDataProcessingRegistrationResponseDTOOrganizationContext;
    general: APIDataProcessingRegistrationResponseDTOGeneral;
    systemUsages: Array<APIIdentityNamePairResponseDTO>;
    oversight: APIDataProcessingRegistrationResponseDTOOversight;
    roles: Array<APIRoleAssignmentResponseDTO>;
    externalReferences: Array<APIExternalReferenceDataResponseDTO>;
}

