/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIExternalUserChangeType } from './externalUserChangeType';


export interface APIExternalUserChangeInput { 
    externalMessageId?: string | null;
    organizationUuid?: string;
    externalUserUuid?: string;
    changeType?: APIExternalUserChangeType;
    occurredAt?: string | null;
}

