/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIGdprCriticalityChoice = 'NotCritical' | 'Low' | 'Medium' | 'High' | 'VeryHigh';

export const APIGdprCriticalityChoice = {
    NotCritical: 'NotCritical' as APIGdprCriticalityChoice,
    Low: 'Low' as APIGdprCriticalityChoice,
    Medium: 'Medium' as APIGdprCriticalityChoice,
    High: 'High' as APIGdprCriticalityChoice,
    VeryHigh: 'VeryHigh' as APIGdprCriticalityChoice
};

