/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIGeneralDataResponseDTONumberOfExpectedUsers } from './generalDataResponseDTONumberOfExpectedUsers';
import { APIYesNoUndecidedChoice } from './yesNoUndecidedChoice';
import { APIYesNoPartiallyChoice } from './yesNoPartiallyChoice';
import { APIGeneralDataResponseDTOValidity } from './generalDataResponseDTOValidity';


export interface APIGeneralDataResponseDTO { 
    localSystemId?: string | null;
    localCallName?: string | null;
    dataClassification?: APIArchivingRegistrationsResponseDTOType | null;
    notes?: string | null;
    systemVersion?: string | null;
    numberOfExpectedUsers?: APIGeneralDataResponseDTONumberOfExpectedUsers | null;
    validity: APIGeneralDataResponseDTOValidity;
    mainContract?: APIArchivingRegistrationsResponseDTOType | null;
    /**
     *  (Supplier Field)
     */
    containsAITechnology?: APIYesNoUndecidedChoice | null;
    webAccessibilityCompliance?: APIYesNoPartiallyChoice | null;
    lastWebAccessibilityCheck?: string | null;
    webAccessibilityNotes?: string | null;
}

