/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIGeneralDataResponseDTONumberOfExpectedUsers } from './generalDataResponseDTONumberOfExpectedUsers';
import { APIYesNoUndecidedChoice } from './yesNoUndecidedChoice';
import { APIGeneralDataUpdateRequestDTOValidity } from './generalDataUpdateRequestDTOValidity';
import { APIYesNoPartiallyChoice } from './yesNoPartiallyChoice';


export interface APIGeneralDataWriteRequestDTO { 
    localSystemId?: string | null;
    localCallName?: string | null;
    dataClassificationUuid?: string | null;
    notes?: string | null;
    systemVersion?: string | null;
    numberOfExpectedUsers?: APIGeneralDataResponseDTONumberOfExpectedUsers | null;
    validity?: APIGeneralDataUpdateRequestDTOValidity | null;
    /**
     *  (Supplier Field)
     */
    containsAITechnology?: APIYesNoUndecidedChoice | null;
    webAccessibilityCompliance?: APIYesNoPartiallyChoice | null;
    lastWebAccessibilityCheck?: string | null;
    webAccessibilityNotes?: string | null;
}

