/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIExpectedUsersIntervalDTO } from './expectedUsersIntervalDTO';
import { APIItSystemUsageValidityWriteRequestDTO } from './itSystemUsageValidityWriteRequestDTO';

export interface APIGeneralDataWriteRequestDTO {
  /**
   *  (Supplier Field)
   */
  localSystemId?: string;
  /**
   * Call name used locally within the organization  Max length: 100
   */
  localCallName?: string;
  /**
   * Optional classification of the registered data  Constraint: If an update changes this field, the option identified must be currently available in the organization context
   */
  dataClassificationUuid?: string;
  /**
   * Notes relevant to the system usage within the organization
   */
  notes?: string;
  /**
   * Locally registered system version  Max length: 100
   */
  systemVersion?: string;
  numberOfExpectedUsers?: APIExpectedUsersIntervalDTO;
  validity?: APIItSystemUsageValidityWriteRequestDTO;
  /**
   * Whether the system usage is known to include any kind of AI technology (Supplier Field)
   */
  containsAITechnology?: APIGeneralDataWriteRequestDTO.ContainsAITechnologyEnum;
  /**
   * Defines if the system is web accessibility compliant
   */
  webAccessibilityCompliance?: APIGeneralDataWriteRequestDTO.WebAccessibilityComplianceEnum;
  /**
   * Last time the supplier checked system web accessibility
   */
  lastWebAccessibilityCheck?: string;
  /**
   * Notes related to the web accessibility of the system
   */
  webAccessibilityNotes?: string;
  /**
   * Whether the system is considered socially critical.
   */
  isSociallyCritical?: APIGeneralDataWriteRequestDTO.IsSociallyCriticalEnum;
}
export namespace APIGeneralDataWriteRequestDTO {
  export type ContainsAITechnologyEnum = 'No' | 'Yes' | 'Undecided';
  export const ContainsAITechnologyEnum = {
    No: 'No' as ContainsAITechnologyEnum,
    Yes: 'Yes' as ContainsAITechnologyEnum,
    Undecided: 'Undecided' as ContainsAITechnologyEnum,
  };
  export type WebAccessibilityComplianceEnum = 'No' | 'Yes' | 'Partially';
  export const WebAccessibilityComplianceEnum = {
    No: 'No' as WebAccessibilityComplianceEnum,
    Yes: 'Yes' as WebAccessibilityComplianceEnum,
    Partially: 'Partially' as WebAccessibilityComplianceEnum,
  };
  export type IsSociallyCriticalEnum = 'No' | 'Yes' | 'DontKnow' | 'Undecided';
  export const IsSociallyCriticalEnum = {
    No: 'No' as IsSociallyCriticalEnum,
    Yes: 'Yes' as IsSociallyCriticalEnum,
    DontKnow: 'DontKnow' as IsSociallyCriticalEnum,
    Undecided: 'Undecided' as IsSociallyCriticalEnum,
  };
}
