/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIGeneralDataResponseDTONumberOfExpectedUsers } from './generalDataResponseDTONumberOfExpectedUsers';
import { APIGeneralDataUpdateRequestDTOValidity } from './generalDataUpdateRequestDTOValidity';

export interface APIGeneralDataUpdateRequestDTO {
  mainContractUuid?: string | null;
  localSystemId?: string | null;
  localCallName?: string | null;
  dataClassificationUuid?: string | null;
  notes?: string | null;
  systemVersion?: string | null;
  numberOfExpectedUsers?: APIGeneralDataResponseDTONumberOfExpectedUsers | null;
  validity?: APIGeneralDataUpdateRequestDTOValidity | null;
  /**
   * Last time the supplier checked system web accessibility
   */
  lastWebAccessibilityCheck?: string;
  /**
   * Notes related to the web accessibility of the system
   */
  webAccessibilityNotes?: string;
}
export namespace APIGeneralDataUpdateRequestDTO {
  export type ContainsAITechnologyEnum = 'No' | 'Yes' | 'Undecided';
  export const ContainsAITechnologyEnum = {
    No: 'No' as ContainsAITechnologyEnum,
    Yes: 'Yes' as ContainsAITechnologyEnum,
    Undecided: 'Undecided' as ContainsAITechnologyEnum,
  };
  export type WebAccessibilityComplianceEnum = 'No' | 'Yes' | 'Partially';
  export const WebAccessibilityComplianceEnum = {
    No: 'No' as WebAccessibilityComplianceEnum,
    Yes: 'Yes' as WebAccessibilityComplianceEnum,
    Partially: 'Partially' as WebAccessibilityComplianceEnum,
  };
}
