/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIGeneralDataResponseDTONumberOfExpectedUsers } from './generalDataResponseDTONumberOfExpectedUsers';
import { APIGeneralDataResponseDTOValidity } from './generalDataResponseDTOValidity';

export interface APIGeneralDataResponseDTO {
  localSystemId?: string | null;
  localCallName?: string | null;
  dataClassification?: APIArchivingRegistrationsResponseDTOType | null;
  notes?: string | null;
  systemVersion?: string | null;
  numberOfExpectedUsers?: APIGeneralDataResponseDTONumberOfExpectedUsers | null;
  validity: APIGeneralDataResponseDTOValidity;
  mainContract?: APIArchivingRegistrationsResponseDTOType | null;
  /**
   *  (Supplier Field)
   */
  containsAITechnology?: APIGeneralDataResponseDTO.ContainsAITechnologyEnum;
  /**
   * Defines if the system is web accessibility compliant
   */
  webAccessibilityCompliance?: APIGeneralDataResponseDTO.WebAccessibilityComplianceEnum;
  /**
   * Last time the supplier checked system web accessibility
   */
  lastWebAccessibilityCheck?: string;
  /**
   * Notes related to the web accessibility of the system
   */
  webAccessibilityNotes?: string;
  /**
   * Whether this system is considered socially critical.
   */
  isSociallyCritical?: APIGeneralDataResponseDTO.IsSociallyCriticalEnum;
}
export namespace APIGeneralDataResponseDTO {
  export type ContainsAITechnologyEnum = 'No' | 'Yes' | 'Undecided';
  export const ContainsAITechnologyEnum = {
    No: 'No' as ContainsAITechnologyEnum,
    Yes: 'Yes' as ContainsAITechnologyEnum,
    Undecided: 'Undecided' as ContainsAITechnologyEnum,
  };
  export type WebAccessibilityComplianceEnum = 'No' | 'Yes' | 'Partially';
  export const WebAccessibilityComplianceEnum = {
    No: 'No' as WebAccessibilityComplianceEnum,
    Yes: 'Yes' as WebAccessibilityComplianceEnum,
    Partially: 'Partially' as WebAccessibilityComplianceEnum,
  };
  export type IsSociallyCriticalEnum = 'No' | 'Yes' | 'DontKnow' | 'Undecided';
  export const IsSociallyCriticalEnum = {
    No: 'No' as IsSociallyCriticalEnum,
    Yes: 'Yes' as IsSociallyCriticalEnum,
    DontKnow: 'DontKnow' as IsSociallyCriticalEnum,
    Undecided: 'Undecided' as IsSociallyCriticalEnum,
  };
}
