/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIExpectedUsersIntervalDTO } from './expectedUsersIntervalDTO';
import { APIItSystemUsageValidityWriteRequestDTO } from './itSystemUsageValidityWriteRequestDTO';
import { APIYesNoDontKnowChoice } from './yesNoDontKnowChoice';
import { APIYesNoPartiallyChoice } from './yesNoPartiallyChoice';
import { APIYesNoUndecidedChoice } from './yesNoUndecidedChoice';

export interface APIGeneralDataWriteRequestDTO {
  localSystemId?: string | null;
  localCallName?: string | null;
  dataClassificationUuid?: string | null;
  notes?: string | null;
  systemVersion?: string | null;
  numberOfExpectedUsers?: APIExpectedUsersIntervalDTO;
  validity?: APIItSystemUsageValidityWriteRequestDTO;
  containsAITechnology?: APIYesNoUndecidedChoice;
  webAccessibilityCompliance?: APIYesNoPartiallyChoice;
  lastWebAccessibilityCheck?: string | null;
  webAccessibilityNotes?: string | null;
  isSociallyCritical?: APIYesNoDontKnowChoice;
  businessCritical?: APIYesNoDontKnowChoice;
}
