/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIContractGeneralDataResponseDTOValidity } from './contractGeneralDataResponseDTOValidity';


export interface APIItContractResponseDTOGeneral { 
    contractId?: string | null;
    contractType?: APIArchivingRegistrationsResponseDTOType | null;
    contractTemplate?: APIArchivingRegistrationsResponseDTOType | null;
    agreementElements: Array<APIIdentityNamePairResponseDTO>;
    notes?: string | null;
    validity: APIContractGeneralDataResponseDTOValidity;
    criticality?: APIArchivingRegistrationsResponseDTOType | null;
}

