/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIContractSupplierDataResponseDTO } from './contractSupplierDataResponseDTO';
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIContractPaymentsDataResponseDTO } from './contractPaymentsDataResponseDTO';
import { APIRoleAssignmentResponseDTO } from './roleAssignmentResponseDTO';
import { APIContractAgreementPeriodDataResponseDTO } from './contractAgreementPeriodDataResponseDTO';
import { APIContractGeneralDataResponseDTO } from './contractGeneralDataResponseDTO';
import { APIContractResponsibleDataResponseDTO } from './contractResponsibleDataResponseDTO';
import { APIShallowOrganizationResponseDTO } from './shallowOrganizationResponseDTO';
import { APIContractPaymentModelDataResponseDTO } from './contractPaymentModelDataResponseDTO';
import { APIContractProcurementDataResponseDTO } from './contractProcurementDataResponseDTO';
import { APIContractTerminationDataResponseDTO } from './contractTerminationDataResponseDTO';
import { APIExternalReferenceDataResponseDTO } from './externalReferenceDataResponseDTO';


export interface APIItContractResponseDTO { 
    uuid: string;
    name: string;
    organizationContext: APIShallowOrganizationResponseDTO;
    lastModified: string;
    lastModifiedBy: APIIdentityNamePairResponseDTO;
    createdBy: APIIdentityNamePairResponseDTO;
    parentContract?: APIIdentityNamePairResponseDTO;
    general: APIContractGeneralDataResponseDTO;
    procurement: APIContractProcurementDataResponseDTO;
    supplier: APIContractSupplierDataResponseDTO;
    responsible: APIContractResponsibleDataResponseDTO;
    systemUsages: Array<APIIdentityNamePairResponseDTO>;
    dataProcessingRegistrations: Array<APIIdentityNamePairResponseDTO>;
    paymentModel: APIContractPaymentModelDataResponseDTO;
    agreementPeriod: APIContractAgreementPeriodDataResponseDTO;
    termination: APIContractTerminationDataResponseDTO;
    payments: APIContractPaymentsDataResponseDTO;
    roles: Array<APIRoleAssignmentResponseDTO>;
    externalReferences: Array<APIExternalReferenceDataResponseDTO>;
}

