/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIRegistrationScopeChoice } from './registrationScopeChoice';
import { APIItInterfaceDataResponseDTO } from './itInterfaceDataResponseDTO';
import { APIShallowOrganizationResponseDTO } from './shallowOrganizationResponseDTO';


export interface APIItInterfaceResponseDTO { 
    uuid: string;
    exposedBySystem?: APIIdentityNamePairResponseDTO;
    name: string;
    interfaceId?: string | null;
    version?: string | null;
    description?: string | null;
    notes?: string | null;
    urlReference?: string | null;
    deactivated: boolean;
    created: string;
    createdBy: APIIdentityNamePairResponseDTO;
    lastModified: string;
    lastModifiedBy: APIIdentityNamePairResponseDTO;
    scope: APIRegistrationScopeChoice;
    itInterfaceType?: APIIdentityNamePairResponseDTO;
    data: Array<APIItInterfaceDataResponseDTO>;
    organizationContext: APIShallowOrganizationResponseDTO;
    rightsHolder: APIShallowOrganizationResponseDTO;
}

