/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIRegistrationScopeChoice } from './registrationScopeChoice';
import { APIItInterfaceDataResponseDTO } from './itInterfaceDataResponseDTO';
import { APIDataProcessingRegistrationResponseDTOCreatedBy } from './dataProcessingRegistrationResponseDTOCreatedBy';
import { APIDataProcessingRegistrationResponseDTOOrganizationContext } from './dataProcessingRegistrationResponseDTOOrganizationContext';


export interface APIItInterfaceResponseDTO { 
    lastModified: string;
    lastModifiedBy: APIDataProcessingRegistrationResponseDTOCreatedBy;
    scope: APIRegistrationScopeChoice;
    itInterfaceType?: APIArchivingRegistrationsResponseDTOType | null;
    data: Array<APIItInterfaceDataResponseDTO>;
    organizationContext: APIDataProcessingRegistrationResponseDTOOrganizationContext;
    rightsHolder: APIDataProcessingRegistrationResponseDTOOrganizationContext;
    uuid: string;
    exposedBySystem?: APIArchivingRegistrationsResponseDTOType | null;
    name: string;
    interfaceId?: string | null;
    version?: string | null;
    description?: string | null;
    notes?: string | null;
    urlReference?: string | null;
    deactivated: boolean;
    created: string;
    createdBy: APIDataProcessingRegistrationResponseDTOCreatedBy;
}

