/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIShallowOrganizationResponseDTO } from './shallowOrganizationResponseDTO';


export interface APIItSystemArchiveResponseDTO { 
    /**
     * Unique identifier for the archive
     */
    uuid: string;
    /**
     * The date when the archive was created
     */
    archivingDate: string;
    /**
     * A reference name for the archive
     */
    referenceName: string | null;
    /**
     * Notes about the archive
     */
    note: string | null;
    organization?: APIShallowOrganizationResponseDTO;
}

