/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIGdprCriticalityChoice } from './gdprCriticalityChoice';
import { APIYesNoDontKnowChoice } from './yesNoDontKnowChoice';
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APITechnicalPrecautionChoice } from './technicalPrecautionChoice';
import { APICreateOversightDateDTOOversightReportLink } from './createOversightDateDTOOversightReportLink';
import { APIDataSensitivityLevelChoice } from './dataSensitivityLevelChoice';
import { APIHostingChoice } from './hostingChoice';
import { APIGDPRPersonalDataChoice } from './gDPRPersonalDataChoice';
import { APIRiskLevelChoice } from './riskLevelChoice';


export interface APIItSystemUsageResponseDTOGdpr { 
    purpose?: string | null;
    businessCritical?: APIYesNoDontKnowChoice | null;
    hostedAt?: APIHostingChoice | null;
    directoryDocumentation?: APICreateOversightDateDTOOversightReportLink | null;
    dataSensitivityLevels: Array<APIDataSensitivityLevelChoice>;
    sensitivePersonData: Array<APIIdentityNamePairResponseDTO>;
    specificPersonalData: Array<APIGDPRPersonalDataChoice>;
    registeredDataCategories: Array<APIIdentityNamePairResponseDTO>;
    technicalPrecautionsInPlace?: APIYesNoDontKnowChoice | null;
    technicalPrecautionsApplied: Array<APITechnicalPrecautionChoice>;
    technicalPrecautionsDocumentation?: APICreateOversightDateDTOOversightReportLink | null;
    userSupervision?: APIYesNoDontKnowChoice | null;
    userSupervisionDate?: string | null;
    userSupervisionDocumentation?: APICreateOversightDateDTOOversightReportLink | null;
    riskAssessmentConducted?: APIYesNoDontKnowChoice | null;
    riskAssessmentConductedDate?: string | null;
    /**
     *  (Supplier Field)
     */
    riskAssessmentResult?: APIRiskLevelChoice | null;
    riskAssessmentDocumentation?: APICreateOversightDateDTOOversightReportLink | null;
    riskAssessmentNotes?: string | null;
    plannedRiskAssessmentDate?: string | null;
    dpiaConducted?: APIYesNoDontKnowChoice | null;
    dpiaDate?: string | null;
    dpiaDocumentation?: APICreateOversightDateDTOOversightReportLink | null;
    retentionPeriodDefined?: APIYesNoDontKnowChoice | null;
    nextDataRetentionEvaluationDate?: string | null;
    dataRetentionEvaluationFrequencyInMonths?: number | null;
    /**
     *  (Supplier Field)
     */
    gdprCriticality?: APIGdprCriticalityChoice | null;
}

