/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIRecommendedArchiveDutyChoice } from './recommendedArchiveDutyChoice';


export interface APIItSystemResponseDTORecommendedArchiveDuty { 
    comment?: string | null;
    id: APIItSystemResponseDTORecommendedArchiveDuty.IdEnum;
}
export namespace APIItSystemResponseDTORecommendedArchiveDuty {
    export type IdEnum = 'Undecided' | 'B' | 'K' | 'NoRecommendation' | 'PreserveDataCanDiscardDocuments' | 'BK' | 'KD' | 'KB';
    export const IdEnum = {
        Undecided: 'Undecided' as IdEnum,
        B: 'B' as IdEnum,
        K: 'K' as IdEnum,
        NoRecommendation: 'NoRecommendation' as IdEnum,
        PreserveDataCanDiscardDocuments: 'PreserveDataCanDiscardDocuments' as IdEnum,
        Bk: 'BK' as IdEnum,
        Kd: 'KD' as IdEnum,
        Kb: 'KB' as IdEnum
    };
}


