/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIOrganizationUsageResponseDTO } from './organizationUsageResponseDTO';
import { APIRoleAssignmentResponseDTO } from './roleAssignmentResponseDTO';
import { APIGDPRRegistrationsResponseDTO } from './gDPRRegistrationsResponseDTO';
import { APILocalKLEDeviationsResponseDTO } from './localKLEDeviationsResponseDTO';
import { APIOutgoingSystemRelationResponseDTO } from './outgoingSystemRelationResponseDTO';
import { APIArchivingRegistrationsResponseDTO } from './archivingRegistrationsResponseDTO';
import { APIShallowOrganizationResponseDTO } from './shallowOrganizationResponseDTO';
import { APIGeneralDataResponseDTO } from './generalDataResponseDTO';
import { APIExternalReferenceDataResponseDTO } from './externalReferenceDataResponseDTO';


export interface APIItSystemUsageResponseDTO { 
    uuid: string;
    createdBy: APIIdentityNamePairResponseDTO;
    lastModified: string;
    lastModifiedBy: APIIdentityNamePairResponseDTO;
    systemContext: APIIdentityNamePairResponseDTO;
    organizationContext: APIShallowOrganizationResponseDTO;
    general: APIGeneralDataResponseDTO;
    roles: Array<APIRoleAssignmentResponseDTO>;
    organizationUsage: APIOrganizationUsageResponseDTO;
    localKLEDeviations: APILocalKLEDeviationsResponseDTO;
    externalReferences: Array<APIExternalReferenceDataResponseDTO>;
    archiving: APIArchivingRegistrationsResponseDTO;
    gdpr: APIGDPRRegistrationsResponseDTO;
    outgoingSystemRelations: Array<APIOutgoingSystemRelationResponseDTO>;
}

