/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIMainContractStateChoice } from './mainContractStateChoice';
import { APILifeCycleStatusChoice } from './lifeCycleStatusChoice';


export interface APIItSystemUsageValidityResponseDTO { 
    valid?: boolean;
    validAccordingToValidityPeriod?: boolean;
    validAccordingToLifeCycle?: boolean;
    validAccordingToMainContract?: boolean;
    mainContractState?: APIItSystemUsageValidityResponseDTO.MainContractStateEnum;
    lifeCycleStatus?: APILifeCycleStatusChoice | null;
    validFrom?: string | null;
    validTo?: string | null;
}
export namespace APIItSystemUsageValidityResponseDTO {
    export type MainContractStateEnum = 'NoContract' | 'Active' | 'Inactive';
    export const MainContractStateEnum = {
        NoContract: 'NoContract' as MainContractStateEnum,
        Active: 'Active' as MainContractStateEnum,
        Inactive: 'Inactive' as MainContractStateEnum
    };
}


