/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIItSystemUsageMigrationV2ResponseDTOTargetUsage } from './itSystemUsageMigrationV2ResponseDTOTargetUsage';


export interface APIItSystemUsageRelationMigrationV2ResponseDTO { 
    toSystem?: APIItSystemUsageMigrationV2ResponseDTOTargetUsage | null;
    fromSystem?: APIItSystemUsageMigrationV2ResponseDTOTargetUsage | null;
    description?: string | null;
    _interface?: APIArchivingRegistrationsResponseDTOType | null;
    frequencyType?: APIArchivingRegistrationsResponseDTOType | null;
    contract?: APIArchivingRegistrationsResponseDTOType | null;
}

