/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIItSystemUsageRelationMigrationV2ResponseDTO } from './itSystemUsageRelationMigrationV2ResponseDTO';
import { APIItSystemUsageMigrationV2ResponseDTOTargetUsage } from './itSystemUsageMigrationV2ResponseDTOTargetUsage';


export interface APIItSystemUsageMigrationV2ResponseDTO { 
    targetUsage?: APIItSystemUsageMigrationV2ResponseDTOTargetUsage | null;
    fromSystem?: APIItSystemUsageMigrationV2ResponseDTOTargetUsage | null;
    toSystem?: APIItSystemUsageMigrationV2ResponseDTOTargetUsage | null;
    affectedContracts?: Array<APIIdentityNamePairResponseDTO> | null;
    affectedRelations?: Array<APIItSystemUsageRelationMigrationV2ResponseDTO> | null;
    affectedDataProcessingRegistrations?: Array<APIIdentityNamePairResponseDTO> | null;
}

