/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIItSystemUsageResponseDTOOrganizationUsage } from './itSystemUsageResponseDTOOrganizationUsage';
import { APIItSystemUsageResponseDTOLocalKLEDeviations } from './itSystemUsageResponseDTOLocalKLEDeviations';
import { APIItSystemUsageResponseDTOArchiving } from './itSystemUsageResponseDTOArchiving';
import { APIRoleAssignmentResponseDTO } from './roleAssignmentResponseDTO';
import { APIOutgoingSystemRelationResponseDTO } from './outgoingSystemRelationResponseDTO';
import { APIDataProcessingRegistrationResponseDTOCreatedBy } from './dataProcessingRegistrationResponseDTOCreatedBy';
import { APIDataProcessingRegistrationResponseDTOOrganizationContext } from './dataProcessingRegistrationResponseDTOOrganizationContext';
import { APIItSystemUsageResponseDTOGeneral } from './itSystemUsageResponseDTOGeneral';
import { APIItSystemUsageResponseDTOGdpr } from './itSystemUsageResponseDTOGdpr';
import { APIExternalReferenceDataResponseDTO } from './externalReferenceDataResponseDTO';


export interface APIItSystemUsageResponseDTO { 
    uuid: string;
    createdBy: APIDataProcessingRegistrationResponseDTOCreatedBy;
    lastModified: string;
    lastModifiedBy: APIDataProcessingRegistrationResponseDTOCreatedBy;
    systemContext: APIDataProcessingRegistrationResponseDTOCreatedBy;
    organizationContext: APIDataProcessingRegistrationResponseDTOOrganizationContext;
    general: APIItSystemUsageResponseDTOGeneral;
    roles: Array<APIRoleAssignmentResponseDTO>;
    organizationUsage: APIItSystemUsageResponseDTOOrganizationUsage;
    localKLEDeviations: APIItSystemUsageResponseDTOLocalKLEDeviations;
    externalReferences: Array<APIExternalReferenceDataResponseDTO>;
    archiving: APIItSystemUsageResponseDTOArchiving;
    gdpr: APIItSystemUsageResponseDTOGdpr;
    outgoingSystemRelations: Array<APIOutgoingSystemRelationResponseDTO>;
}

