/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIKLEUpdateStatusChoice = 0 | 1;

export const APIKLEUpdateStatusChoice = {
    NUMBER_0: 0 as APIKLEUpdateStatusChoice,
    NUMBER_1: 1 as APIKLEUpdateStatusChoice
};

