/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIRecipientResponseDTO } from './recipientResponseDTO';
import { APIRepetitionFrequencyOptions } from './repetitionFrequencyOptions';
import { APINotificationSendType } from './notificationSendType';
import { APIOwnerResourceType } from './ownerResourceType';


export interface APINotificationResponseDTO { 
    uuid?: string;
    active?: boolean;
    name?: string | null;
    lastSent?: string | null;
    fromDate?: string | null;
    toDate?: string | null;
    subject?: string | null;
    body?: string | null;
    ownerResourceType?: APIOwnerResourceType;
    notificationType?: APINotificationSendType;
    ownerResource?: APIIdentityNamePairResponseDTO;
    repetitionFrequency?: APIRepetitionFrequencyOptions;
    receivers?: APIRecipientResponseDTO;
    cCs?: APIRecipientResponseDTO;
}

