/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APINotificationResponseDTOReceivers } from './notificationResponseDTOReceivers';
import { APIRepetitionFrequencyOptions } from './repetitionFrequencyOptions';
import { APINotificationSendType } from './notificationSendType';
import { APIOwnerResourceType } from './ownerResourceType';


export interface APINotificationResponseDTO { 
    uuid?: string;
    active?: boolean;
    name?: string | null;
    lastSent?: string | null;
    fromDate?: string | null;
    toDate?: string | null;
    subject?: string | null;
    body?: string | null;
    ownerResourceType?: APINotificationResponseDTO.OwnerResourceTypeEnum;
    notificationType?: APINotificationResponseDTO.NotificationTypeEnum;
    ownerResource?: APIArchivingRegistrationsResponseDTOType | null;
    repetitionFrequency?: APIRepetitionFrequencyOptions | null;
    receivers?: APINotificationResponseDTOReceivers | null;
    cCs?: APINotificationResponseDTOReceivers | null;
}
export namespace APINotificationResponseDTO {
    export type OwnerResourceTypeEnum = 'ItContract' | 'ItSystemUsage' | 'DataProcessingRegistration';
    export const OwnerResourceTypeEnum = {
        ItContract: 'ItContract' as OwnerResourceTypeEnum,
        ItSystemUsage: 'ItSystemUsage' as OwnerResourceTypeEnum,
        DataProcessingRegistration: 'DataProcessingRegistration' as OwnerResourceTypeEnum
    };
    export type NotificationTypeEnum = 'Immediate' | 'Repeat';
    export const NotificationTypeEnum = {
        Immediate: 'Immediate' as NotificationTypeEnum,
        Repeat: 'Repeat' as NotificationTypeEnum
    };
}


