/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIOrganizationType = 1 | 2 | 3 | 4;

export const APIOrganizationType = {
    NUMBER_1: 1 as APIOrganizationType,
    NUMBER_2: 2 as APIOrganizationType,
    NUMBER_3: 3 as APIOrganizationType,
    NUMBER_4: 4 as APIOrganizationType
};

