/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIOrganizationMasterDataRolesResponseDTODataProtectionAdvisor } from './organizationMasterDataRolesResponseDTODataProtectionAdvisor';
import { APIOrganizationMasterDataRolesResponseDTODataResponsible } from './organizationMasterDataRolesResponseDTODataResponsible';
import { APIOrganizationMasterDataRolesResponseDTOContactPerson } from './organizationMasterDataRolesResponseDTOContactPerson';


export interface APIOrganizationMasterDataRolesResponseDTO { 
    organizationUuid?: string;
    contactPerson?: APIOrganizationMasterDataRolesResponseDTOContactPerson | null;
    dataResponsible?: APIOrganizationMasterDataRolesResponseDTODataResponsible | null;
    dataProtectionAdvisor?: APIOrganizationMasterDataRolesResponseDTODataProtectionAdvisor | null;
}

