/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIOrganizationType } from './organizationType';


export interface APIOrganizationResponseDTO { 
    organizationType: APIOrganizationResponseDTO.OrganizationTypeEnum;
    isSupplier?: boolean;
    disabled?: boolean;
    cvr?: string | null;
    uuid: string;
    name: string;
}
export namespace APIOrganizationResponseDTO {
    export type OrganizationTypeEnum = 'Municipality' | 'CommunityOfInterest' | 'Company' | 'OtherPublicAuthority';
    export const OrganizationTypeEnum = {
        Municipality: 'Municipality' as OrganizationTypeEnum,
        CommunityOfInterest: 'CommunityOfInterest' as OrganizationTypeEnum,
        Company: 'Company' as OrganizationTypeEnum,
        OtherPublicAuthority: 'OtherPublicAuthority' as OrganizationTypeEnum
    };
}


