/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIOrganizationUserRole } from './organizationUserRole';


export interface APIOrganizationUserResponseDTO { 
    uuid: string;
    name: string;
    firstName: string;
    lastName?: string | null;
    email: string;
    phoneNumber?: string | null;
    apiAccess: boolean;
    roles: Array<APIOrganizationUserRole>;
}

