/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIOrganizationUserRole = 0 | 1 | 2 | 4 | 5 | 7;

export const APIOrganizationUserRole = {
    NUMBER_0: 0 as APIOrganizationUserRole,
    NUMBER_1: 1 as APIOrganizationUserRole,
    NUMBER_2: 2 as APIOrganizationUserRole,
    NUMBER_4: 4 as APIOrganizationUserRole,
    NUMBER_5: 5 as APIOrganizationUserRole,
    NUMBER_7: 7 as APIOrganizationUserRole
};

