/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIOrganizationType } from './organizationType';


export interface APIOrganizationResponseDTO { 
    uuid: string;
    name: string;
    cvr?: string | null;
    organizationType: APIOrganizationType;
    isSupplier?: boolean;
    disabled?: boolean;
}

