/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIColumnConfigurationResponseDTO } from './columnConfigurationResponseDTO';
import { APIOverviewType } from './overviewType';


export interface APIOrganizationGridConfigurationResponseDTO { 
    organizationUuid?: string;
    overviewType?: APIOrganizationGridConfigurationResponseDTO.OverviewTypeEnum;
    visibleColumns?: Array<APIColumnConfigurationResponseDTO> | null;
}
export namespace APIOrganizationGridConfigurationResponseDTO {
    export type OverviewTypeEnum = 'ItSystemUsage' | 'ItContract' | 'DataProcessingRegistration';
    export const OverviewTypeEnum = {
        ItSystemUsage: 'ItSystemUsage' as OverviewTypeEnum,
        ItContract: 'ItContract' as OverviewTypeEnum,
        DataProcessingRegistration: 'DataProcessingRegistration' as OverviewTypeEnum
    };
}


