/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIRegistrationScopeChoice } from './registrationScopeChoice';
import { APIItInterfaceDataRequestDTO } from './itInterfaceDataRequestDTO';


export interface APIPatchSingleItInterfaceV2PatchRequest { 
    exposedBySystemUuid?: string | null;
    deactivated?: boolean;
    scope?: APIPatchSingleItInterfaceV2PatchRequest.ScopeEnum;
    itInterfaceTypeUuid?: string | null;
    data?: Array<APIItInterfaceDataRequestDTO> | null;
    note?: string | null;
    name?: string | null;
    interfaceId?: string | null;
    version?: string | null;
    description?: string | null;
    urlReference?: string | null;
}
export namespace APIPatchSingleItInterfaceV2PatchRequest {
    export type ScopeEnum = 'Local' | 'Global';
    export const ScopeEnum = {
        Local: 'Local' as ScopeEnum,
        Global: 'Global' as ScopeEnum
    };
}


