/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIPaymentResponseDTOOrganizationUnit } from './paymentResponseDTOOrganizationUnit';
import { APIPaymentAuditStatus } from './paymentAuditStatus';


export interface APIPaymentResponseDTO { 
    id?: number;
    organizationUnit?: APIPaymentResponseDTOOrganizationUnit | null;
    acquisition?: number;
    operation?: number;
    other?: number;
    accountingEntry?: string | null;
    auditStatus?: APIPaymentResponseDTO.AuditStatusEnum;
    auditDate?: string | null;
    note?: string | null;
}
export namespace APIPaymentResponseDTO {
    export type AuditStatusEnum = 'White' | 'Red' | 'Yellow' | 'Green';
    export const AuditStatusEnum = {
        White: 'White' as AuditStatusEnum,
        Red: 'Red' as AuditStatusEnum,
        Yellow: 'Yellow' as AuditStatusEnum,
        Green: 'Green' as AuditStatusEnum
    };
}


