/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIPaymentAuditStatus = 0 | 1 | 2 | 3;

export const APIPaymentAuditStatus = {
    NUMBER_0: 0 as APIPaymentAuditStatus,
    NUMBER_1: 1 as APIPaymentAuditStatus,
    NUMBER_2: 2 as APIPaymentAuditStatus,
    NUMBER_3: 3 as APIPaymentAuditStatus
};

