/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIExternalReferenceDataWriteRequestDTO } from './externalReferenceDataWriteRequestDTO';
import { APICreateItSystemRequestDTORecommendedArchiveDuty } from './createItSystemRequestDTORecommendedArchiveDuty';
import { APIRegistrationScopeChoice } from './registrationScopeChoice';


export interface APIPostSingleItSystemV2PostItSystemRequest { 
    organizationUuid: string;
    parentUuid?: string | null;
    name: string;
    previousName?: string | null;
    description?: string | null;
    externalReferences?: Array<APIExternalReferenceDataWriteRequestDTO> | null;
    businessTypeUuid?: string | null;
    kleUuids?: Array<string> | null;
    rightsHolderUuid?: string | null;
    scope?: APIRegistrationScopeChoice | null;
    recommendedArchiveDuty?: APICreateItSystemRequestDTORecommendedArchiveDuty | null;
    deactivated?: boolean;
}

