/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIOrganizationUnitOriginChoice } from './organizationUnitOriginChoice';


export interface APIPostSingleOrganizationUnitsInternalV2CreateUnitRequest { 
    name?: string | null;
    origin?: APIPostSingleOrganizationUnitsInternalV2CreateUnitRequest.OriginEnum;
    parentUuid?: string;
    ean?: number | null;
    localId?: string | null;
}
export namespace APIPostSingleOrganizationUnitsInternalV2CreateUnitRequest {
    export type OriginEnum = 'Kitos' | 'STSOrganisation';
    export const OriginEnum = {
        Kitos: 'Kitos' as OriginEnum,
        StsOrganisation: 'STSOrganisation' as OriginEnum
    };
}


