/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIRegistrationScopeChoice } from './registrationScopeChoice';
import { APIItInterfaceDataRequestDTO } from './itInterfaceDataRequestDTO';


export interface APIPostSingleItInterfaceV2PostRequest { 
    organizationUuid: string;
    exposedBySystemUuid?: string | null;
    deactivated?: boolean;
    scope?: APIRegistrationScopeChoice;
    itInterfaceTypeUuid?: string | null;
    data?: Array<APIItInterfaceDataRequestDTO> | null;
    note?: string | null;
    name: string;
    interfaceId?: string | null;
    version?: string | null;
    description?: string | null;
    urlReference?: string | null;
}

