/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIPublicMessageIconTypeChoice = 0 | 1 | 2 | 3 | 4 | 5;

export const APIPublicMessageIconTypeChoice = {
    NUMBER_0: 0 as APIPublicMessageIconTypeChoice,
    NUMBER_1: 1 as APIPublicMessageIconTypeChoice,
    NUMBER_2: 2 as APIPublicMessageIconTypeChoice,
    NUMBER_3: 3 as APIPublicMessageIconTypeChoice,
    NUMBER_4: 4 as APIPublicMessageIconTypeChoice,
    NUMBER_5: 5 as APIPublicMessageIconTypeChoice
};

