/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIPublicMessageStatusChoice = 1 | 2;

export const APIPublicMessageStatusChoice = {
    NUMBER_1: 1 as APIPublicMessageStatusChoice,
    NUMBER_2: 2 as APIPublicMessageStatusChoice
};

