/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIContractWriteRequestDTOSupplier } from './contractWriteRequestDTOSupplier';
import { APIUpdateExternalReferenceDataWriteRequestDTO } from './updateExternalReferenceDataWriteRequestDTO';
import { APIContractWriteRequestDTOPayments } from './contractWriteRequestDTOPayments';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';
import { APIContractWriteRequestDTOPaymentModel } from './contractWriteRequestDTOPaymentModel';
import { APIContractWriteRequestDTOTermination } from './contractWriteRequestDTOTermination';
import { APIContractWriteRequestDTOAgreementPeriod } from './contractWriteRequestDTOAgreementPeriod';
import { APIContractWriteRequestDTOGeneral } from './contractWriteRequestDTOGeneral';
import { APIContractWriteRequestDTOProcurement } from './contractWriteRequestDTOProcurement';
import { APIContractWriteRequestDTOResponsible } from './contractWriteRequestDTOResponsible';


export interface APIPutSingleItContractV2PutItContractRequest { 
    name?: string | null;
    externalReferences?: Array<APIUpdateExternalReferenceDataWriteRequestDTO> | null;
    parentContractUuid?: string | null;
    general?: APIContractWriteRequestDTOGeneral | null;
    procurement?: APIContractWriteRequestDTOProcurement | null;
    supplier?: APIContractWriteRequestDTOSupplier | null;
    responsible?: APIContractWriteRequestDTOResponsible | null;
    systemUsageUuids?: Array<string> | null;
    dataProcessingRegistrationUuids?: Array<string> | null;
    paymentModel?: APIContractWriteRequestDTOPaymentModel | null;
    agreementPeriod?: APIContractWriteRequestDTOAgreementPeriod | null;
    termination?: APIContractWriteRequestDTOTermination | null;
    payments?: APIContractWriteRequestDTOPayments | null;
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
}

