/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APIRepetitionFrequencyOptions = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const APIRepetitionFrequencyOptions = {
    NUMBER_0: 0 as APIRepetitionFrequencyOptions,
    NUMBER_1: 1 as APIRepetitionFrequencyOptions,
    NUMBER_2: 2 as APIRepetitionFrequencyOptions,
    NUMBER_3: 3 as APIRepetitionFrequencyOptions,
    NUMBER_4: 4 as APIRepetitionFrequencyOptions,
    NUMBER_5: 5 as APIRepetitionFrequencyOptions,
    NUMBER_6: 6 as APIRepetitionFrequencyOptions
};

