/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface APIRightsHolderCreateItInterfaceRequestDTO { 
    exposedBySystemUuid: string;
    name: string;
    interfaceId?: string | null;
    version?: string | null;
    description: string;
    urlReference: string;
    rightsHolderUuid: string;
    uuid?: string | null;
}

