/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface APIRightsHolderPartialUpdateItInterfaceRequestDTO { 
    name?: string | null;
    exposedBySystemUuid?: string;
    interfaceId?: string | null;
    version?: string | null;
    description?: string | null;
    urlReference?: string | null;
}

