/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIDataProcessingRegistrationResponseDTOCreatedBy } from './dataProcessingRegistrationResponseDTOCreatedBy';


export interface APIRightsHolderItInterfaceResponseDTO { 
    uuid: string;
    exposedBySystem?: APIArchivingRegistrationsResponseDTOType | null;
    name: string;
    interfaceId?: string | null;
    version?: string | null;
    description?: string | null;
    notes?: string | null;
    urlReference?: string | null;
    deactivated: boolean;
    created: string;
    createdBy: APIDataProcessingRegistrationResponseDTOCreatedBy;
}

