/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIIdentityNamePairResponseDTO } from './identityNamePairResponseDTO';
import { APIArchivingRegistrationsResponseDTOSupplier } from './archivingRegistrationsResponseDTOSupplier';
import { APIShallowOrganizationResponseDTO } from './shallowOrganizationResponseDTO';
import { APIDataProcessingRegistrationResponseDTOCreatedBy } from './dataProcessingRegistrationResponseDTOCreatedBy';
import { APIItSystemResponseDTORecommendedArchiveDuty } from './itSystemResponseDTORecommendedArchiveDuty';
import { APIExternalReferenceDataResponseDTO } from './externalReferenceDataResponseDTO';


export interface APIRightsHolderItSystemResponseDTO { 
    uuid: string;
    externalUuid?: string | null;
    parentSystem?: APIArchivingRegistrationsResponseDTOType | null;
    name: string;
    formerName?: string | null;
    description?: string | null;
    externalReferences: Array<APIExternalReferenceDataResponseDTO>;
    kle: Array<APIIdentityNamePairResponseDTO>;
    deactivated: boolean;
    businessType?: APIArchivingRegistrationsResponseDTOType | null;
    rightsHolder?: APIArchivingRegistrationsResponseDTOSupplier | null;
    created: string;
    createdBy: APIDataProcessingRegistrationResponseDTOCreatedBy;
    recommendedArchiveDuty: APIItSystemResponseDTORecommendedArchiveDuty;
    mainContractSuppliers: Array<APIShallowOrganizationResponseDTO>;
}

