/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIStsOrganizationAccessStatusResponseDTO } from './stsOrganizationAccessStatusResponseDTO';


/**
 * Status of the FK Organisation users connection. Independent of the org-unit connection.
 */
export interface APIStsOrganizationUserSynchronizationDetailsResponseDTO { 
    accessStatus: APIStsOrganizationAccessStatusResponseDTO;
    /**
     * Determines if KITOS accepts external user changes from FK Organisation for the organization
     */
    connected?: boolean;
    canCreateConnection?: boolean;
    canDeleteConnection?: boolean;
    /**
     * UTC time when the connection was created. Null if not connected.
     */
    connectedAt?: string | null;
}

