/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIStsOrganizationChangeLogOriginOption } from './stsOrganizationChangeLogOriginOption';
import { APIConnectionUpdateOrganizationUnitConsequenceDTO } from './connectionUpdateOrganizationUnitConsequenceDTO';
import { APIStsOrganizationChangeLogResponseDTOUser } from './stsOrganizationChangeLogResponseDTOUser';


export interface APIStsOrganizationChangeLogResponseDTO { 
    origin?: APIStsOrganizationChangeLogResponseDTO.OriginEnum;
    user?: APIStsOrganizationChangeLogResponseDTOUser | null;
    logTime?: string;
    consequences?: Array<APIConnectionUpdateOrganizationUnitConsequenceDTO> | null;
}
export namespace APIStsOrganizationChangeLogResponseDTO {
    export type OriginEnum = 'Background' | 'User';
    export const OriginEnum = {
        Background: 'Background' as OriginEnum,
        User: 'User' as OriginEnum
    };
}


