/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APITrackedEntityTypeChoice } from './trackedEntityTypeChoice';


export interface APITrackingEventResponseDTO { 
    occurredAtUtc: string;
    entityUuid: string;
    entityType: APITrackingEventResponseDTO.EntityTypeEnum;
}
export namespace APITrackingEventResponseDTO {
    export type EntityTypeEnum = 'ItSystem' | 'ItSystemUsage' | 'ItInterface' | 'ItContract' | 'DataProcessingRegistration' | 'OrganizationUnit';
    export const EntityTypeEnum = {
        ItSystem: 'ItSystem' as EntityTypeEnum,
        ItSystemUsage: 'ItSystemUsage' as EntityTypeEnum,
        ItInterface: 'ItInterface' as EntityTypeEnum,
        ItContract: 'ItContract' as EntityTypeEnum,
        DataProcessingRegistration: 'DataProcessingRegistration' as EntityTypeEnum,
        OrganizationUnit: 'OrganizationUnit' as EntityTypeEnum
    };
}


