/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type APITrackedEntityTypeChoice = 0 | 1 | 2 | 3 | 4 | 6;

export const APITrackedEntityTypeChoice = {
    NUMBER_0: 0 as APITrackedEntityTypeChoice,
    NUMBER_1: 1 as APITrackedEntityTypeChoice,
    NUMBER_2: 2 as APITrackedEntityTypeChoice,
    NUMBER_3: 3 as APITrackedEntityTypeChoice,
    NUMBER_4: 4 as APITrackedEntityTypeChoice,
    NUMBER_6: 6 as APITrackedEntityTypeChoice
};

