/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APICreateDataProcessingRegistrationRequestDTOGeneral } from './createDataProcessingRegistrationRequestDTOGeneral';
import { APICreateDataProcessingRegistrationRequestDTOOversight } from './createDataProcessingRegistrationRequestDTOOversight';
import { APIUpdateExternalReferenceDataWriteRequestDTO } from './updateExternalReferenceDataWriteRequestDTO';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';


export interface APIUpdateDataProcessingRegistrationRequestDTO { 
    name?: string | null;
    externalReferences?: Array<APIUpdateExternalReferenceDataWriteRequestDTO> | null;
    general?: APICreateDataProcessingRegistrationRequestDTOGeneral | null;
    systemUsageUuids?: Array<string> | null;
    oversight?: APICreateDataProcessingRegistrationRequestDTOOversight | null;
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
}

