/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APILocalKLEDeviationsRequestDTO } from './localKLEDeviationsRequestDTO';
import { APIArchivingUpdateRequestDTO } from './archivingUpdateRequestDTO';
import { APIGeneralDataUpdateRequestDTO } from './generalDataUpdateRequestDTO';
import { APIOrganizationUsageWriteRequestDTO } from './organizationUsageWriteRequestDTO';
import { APIUpdateExternalReferenceDataWriteRequestDTO } from './updateExternalReferenceDataWriteRequestDTO';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';
import { APIGDPRWriteRequestDTO } from './gDPRWriteRequestDTO';


export interface APIUpdateItSystemUsageRequestDTO { 
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
    organizationUsage?: APIOrganizationUsageWriteRequestDTO;
    localKleDeviations?: APILocalKLEDeviationsRequestDTO;
    gdpr?: APIGDPRWriteRequestDTO;
    general?: APIGeneralDataUpdateRequestDTO;
    externalReferences?: Array<APIUpdateExternalReferenceDataWriteRequestDTO> | null;
    archiving?: APIArchivingUpdateRequestDTO;
}

