/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APICreateItSystemUsageRequestDTOOrganizationUsage } from './createItSystemUsageRequestDTOOrganizationUsage';
import { APICreateItSystemUsageRequestDTOLocalKleDeviations } from './createItSystemUsageRequestDTOLocalKleDeviations';
import { APICreateItSystemUsageRequestDTOGdpr } from './createItSystemUsageRequestDTOGdpr';
import { APIUpdateExternalReferenceDataWriteRequestDTO } from './updateExternalReferenceDataWriteRequestDTO';
import { APIRoleAssignmentRequestDTO } from './roleAssignmentRequestDTO';
import { APIUpdateItSystemUsageRequestDTOArchiving } from './updateItSystemUsageRequestDTOArchiving';
import { APIUpdateItSystemUsageRequestDTOGeneral } from './updateItSystemUsageRequestDTOGeneral';


export interface APIUpdateItSystemUsageRequestDTO { 
    general?: APIUpdateItSystemUsageRequestDTOGeneral | null;
    externalReferences?: Array<APIUpdateExternalReferenceDataWriteRequestDTO> | null;
    archiving?: APIUpdateItSystemUsageRequestDTOArchiving | null;
    roles?: Array<APIRoleAssignmentRequestDTO> | null;
    organizationUsage?: APICreateItSystemUsageRequestDTOOrganizationUsage | null;
    localKleDeviations?: APICreateItSystemUsageRequestDTOLocalKleDeviations | null;
    gdpr?: APICreateItSystemUsageRequestDTOGdpr | null;
}

