/**
 * KITOS API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { APIArchivingRegistrationsResponseDTOType } from './archivingRegistrationsResponseDTOType';
import { APIOrganizationRoleChoice } from './organizationRoleChoice';
import { APIDefaultUserStartPreferenceChoice } from './defaultUserStartPreferenceChoice';


export interface APIUserResponseDTO { 
    uuid?: string;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    phoneNumber?: string | null;
    defaultUserStartPreference?: APIUserResponseDTO.DefaultUserStartPreferenceEnum;
    hasApiAccess?: boolean | null;
    hasStakeHolderAccess?: boolean;
    roles?: Array<APIOrganizationRoleChoice> | null;
    defaultOrganizationUnit?: APIArchivingRegistrationsResponseDTOType | null;
    lastSentAdvis?: string | null;
}
export namespace APIUserResponseDTO {
    export type DefaultUserStartPreferenceEnum = 'StartSite' | 'Organization' | 'ItSystemUsage' | 'ItSystemCatalog' | 'ItContract' | 'DataProcessing';
    export const DefaultUserStartPreferenceEnum = {
        StartSite: 'StartSite' as DefaultUserStartPreferenceEnum,
        Organization: 'Organization' as DefaultUserStartPreferenceEnum,
        ItSystemUsage: 'ItSystemUsage' as DefaultUserStartPreferenceEnum,
        ItSystemCatalog: 'ItSystemCatalog' as DefaultUserStartPreferenceEnum,
        ItContract: 'ItContract' as DefaultUserStartPreferenceEnum,
        DataProcessing: 'DataProcessing' as DefaultUserStartPreferenceEnum
    };
}


