name: Cypress Tests
on:
  pull_request:
    types:
      - ready_for_review # Trigger when a draft PR is converted to non-draft
      - synchronize # Trigger on subsequent pushes to the PR
  push:
    branches:
      - main # Runs on merges to the main branch
  workflow_dispatch:

jobs:
  cypress-run:
    if: github.event.pull_request == null || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 300
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_TO_GITHUB }}

  cypress-component:
    if: github.event.pull_request == null || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          command: yarn cypress run --component
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_TO_GITHUB }}
