name: Cypress Tests
on:
  pull_request:
    types:
      - ready_for_review # Trigger when a draft PR is converted to non-draft
      - synchronize # Trigger on subsequent pushes to the PR
  push:
    branches:
      - main # Runs on merges to the main branch
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build Angular app
        run: ng build --configuration=production

      - name: Start static server
        run: npx http-server dist/kitos-web -p 4200 &
        env:
          CI: true

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:4200

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_TO_GITHUB }}
